// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoUl7oFDJ2ii2TOaLxbbSvvd91iMnK89c',
    appId: '1:259293313676:web:ecd0ce20f1873170b619a9',
    messagingSenderId: '259293313676',
    projectId: 'drive-app-936f3',
    authDomain: 'drive-app-936f3.firebaseapp.com',
    storageBucket: 'drive-app-936f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvAOwG-jilnoEsoDWYmBCTuJhD6cLs_GQ',
    appId: '1:259293313676:android:d228306a17b35a01b619a9',
    messagingSenderId: '259293313676',
    projectId: 'drive-app-936f3',
    storageBucket: 'drive-app-936f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzeefvVLf3KJ95Q4WyZ7aiJX7Xwdg_8dM',
    appId: '1:259293313676:ios:adb4288a226a80e7b619a9',
    messagingSenderId: '259293313676',
    projectId: 'drive-app-936f3',
    storageBucket: 'drive-app-936f3.appspot.com',
    iosBundleId: 'com.example.driveApp',
  );
}
